# Generated by Django 5.1 on 2024-08-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelnews',
            options={'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
        migrations.AddField(
            model_name='modelnews',
            name='content',
            field=models.FileField(default='Default content', upload_to='media/'),
        ),
    ]
